n=int(input("DIgite um numero para ver a tabuada: "))
print(n,"X", 1, n*1)
print(n,"X", 2, n*2)
print(n,"X", 3, n*3)
print(n,"X", 4, n*4)
print(n,"X", 5, n*5)
print(n,"X", 6, n*6)
print(n,"X", 7, n*7)
print(n,"X", 8, n*8)
print(n,"X", 9, n*9)
print(n,"X", 10, n*10)
